#ifndef VERSION_UTILS_H_IN
#define VERSION_UTILS_H_IN

#define EYS3D_DEPTH_VERSION_MAJOR 1
#define EYS3D_DEPTH_VERSION_MINOR 0
#define EYS3D_DEPTH_VERSION_PATCH 0
#define EYS3D_DEPTH_VERSION_TWEAK 1

#define WRAPPER_VERSION "1.0.0.1"
#define GIT_BRANCH "release_windows_python_wrapper"
#define GIT_HASH "30acdfe4"
#define BUILD_TIMESTAMP "2023-08-07 17:44:36"

#endif // VERSION_UTILS_H_IN
